name: tal3a
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.0.0
  flutter_screenutil: ^5.9.0
  http: ^1.1.0
  get_it: ^7.6.4
  fpdart: ^1.1.0
  lottie: ^3.1.2
  animate_do: ^3.3.4
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  confetti: ^0.7.0
  rive: ^0.13.1
  flutter_svg: ^1.1.6
  fluid_bottom_nav_bar: ^1.4.0
  google_fonts: ^6.3.1
  google_maps_flutter: ^2.8.0
  video_player: ^2.8.2
  easy_localization: ^3.0.7
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  path: ^1.8.3
  permission_handler: ^11.3.0
  image: ^4.1.7
  equatable: ^2.0.5
  photo_manager: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_image_filters: ^0.0.32
  image_editor: ^1.0.2
  geocoding: ^2.0.5
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Urbanist
      fonts:
        - asset: fonts/Urbanist-Thin.ttf
          weight: 100
        - asset: fonts/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: fonts/Urbanist-Light.ttf
          weight: 300
        - asset: fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: fonts/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: fonts/Urbanist-Black.ttf
          weight: 900
        - asset: fonts/Urbanist-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Urbanist-ExtraLightItalic.ttf
          weight: 200
          style: italic
    - family: WorkSans
      fonts:
        - asset: fonts/WorkSans-Thin.ttf
          weight: 100
        - asset: fonts/WorkSans-ExtraLight.ttf
          weight: 200
        - asset: fonts/WorkSans-Light.ttf
          weight: 300
        - asset: fonts/WorkSans-Regular.ttf
          weight: 400
        - asset: fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: fonts/WorkSans-Bold.ttf
          weight: 700
        - asset: fonts/WorkSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/WorkSans-Black.ttf
          weight: 900
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Light.ttf
          weight: 300
        - asset: fonts/Rubik-Regular.ttf
          weight: 400
        - asset: fonts/Rubik-Medium.ttf
          weight: 500
        - asset: fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: fonts/Rubik-Bold.ttf
          weight: 700
        - asset: fonts/Rubik-ExtraBold.ttf
          weight: 800
        - asset: fonts/Rubik-Black.ttf
          weight: 900
        - asset: fonts/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Rubik-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Rubik-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Inter
      fonts:
        - asset: fonts/Inter_24pt-Thin.ttf
          weight: 100
        - asset: fonts/Inter_24pt-ExtraLight.ttf
          weight: 200
        - asset: fonts/Inter_24pt-Light.ttf
          weight: 300
        - asset: fonts/Inter_24pt-Regular.ttf
          weight: 400
        - asset: fonts/Inter_24pt-Medium.ttf
          weight: 500
        - asset: fonts/Inter_24pt-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter_24pt-Bold.ttf
          weight: 700
        - asset: fonts/Inter_24pt-ExtraBold.ttf
          weight: 800
        - asset: fonts/Inter_24pt-Black.ttf
          weight: 900
        - asset: fonts/Inter_24pt-Italic.ttf
          weight: 400
          style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
